# Catppuccin Macchiato - Two-line prompt

scan_timeout = 600
command_timeout = 7000
add_newline = false

format = """
$username\
[@](bold fg:text)\
$directory\
[ in ](bold fg:text)\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$python\
$line_break\
$character"""

palette = 'catppuccin_macchiato'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[username]
show_always = true
style_user = "bold fg:red"
format = '[$user]($style)'

[directory]
style = "bold fg:blue"
format = "[$path]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " 󰌾"
home_symbol = "~"

[git_branch]
symbol = " "
style = "bold fg:mauve"
format = '[[ ](bold fg:mauve)\($branch\)]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))' 
conflicted = "[ 󰞇 ](bold fg:red)"
ahead = "[ 󰶣 ](bold fg:green)"
behind = "[ 󰶡 ](bold fg:red)"
diverged = "[ 󰹹 ](bold fg:peach)"
untracked = "[ 󰳟 ](bold fg:mauve)"
stashed = "[ 󰳦 ](bold fg:blue)"
modified = "[ 󰷈 ](bold fg:red)"    
staged = "[ 󰐗 ](bold fg:green)"    
renamed = "[ 󰖷 ](bold fg:yellow)"
deleted = "[ 󰆴 ](bold fg:red)"

[nodejs]
symbol = " "
style = "fg:green"
format = '[ $symbol$version]($style)'

[rust]
symbol = " "
style = "fg:green"
format = '[ $symbol$version]($style)'

[golang]
symbol = " "
style = "fg:green"
format = '[ $symbol$version]($style)'

[python]
symbol = " "
style = "fg:green"
format = '[ $symbol$version]($style)'

[character]
success_symbol = '[-λ](bold green)'
error_symbol = '[-λ](bold red)'

[line_break]
disabled = false
